### ISSUE TITLE
overlapping

### ISSUE THREAD

**Issue by r20222** [Nazneen05x/the-web-is-for-everyone-interactive-functionality#12]
Ik zie dat de footer overlapt met de afbeelding, misschien is dat op te lossen met footer{ margin-top: 3rem;}  ofzoiets?

![image](https://user-images.githubusercontent.com/101579892/229138925-d2a2f8dd-5baf-4c7a-b61e-7808aa05966e.png)

**Comment by Nazneen05x** [comment]
Thanks voor de feedback!

https://pear-sunbonnet.cyclic.app/
